=== appserver-io-php/runtime/src/var/www/chapter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/chapter"
	xmlns:tns="http://www.example.org/chapter"
	elementFormDefault="unqualified"
	attributeFormDefault="unqualified">
	<xs:element name="chapter">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="tns:title" />
				<xs:element ref="tns:para" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="title">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="para">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="tns:row" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="row">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="tns:entry" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="entry">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== appserver-io-php/runtime/src/var/www/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<para  xsi:schemaLocation="http://www.example.org/chapter chapter.xsd">
	<row>
		<entry>The Grapes of Wrath</entry>
		<entry>John Steinbeck</entry>
		<entry>en</entry>
		<entry>0140186409</entry>
	</row>
	<row>
		<entry>The Pearl</entry>
		<entry>John Steinbeck</entry>
		<entry>en</entry>
		<entry>014017737X</entry>
	</row>
	<row>
		<entry>Samarcande</entry>
		<entry>Amine Maalouf</entry>
		<entry>fr</entry>
		<entry>2253051209</entry>
	</row>
</para>
